/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimientos.cobros;

import movimientos.recepcion.*;
import movimientos.servicios.*;
import buscadores.*;
import referenciales.*;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import menu.menu;

/**
 *
 * @author hpnotebook
 */
public class detalle_cobros extends javax.swing.JInternalFrame {

    conexion.conexion con = new conexion.conexion();
    javax.swing.table.DefaultTableModel t, t1;
    DecimalFormat num = new DecimalFormat("#,##0");
    SimpleDateFormat fec = new SimpleDateFormat("dd/MM/yyyy");
    
     private String id_tabla="nada";
     
     private String formulario="";
     
     int f = -1;
     int c = -1;
     String tabla[][];
     int precio=0;
     String idd[];
    public detalle_cobros(String formulario, String pasar, String pasar1) {
        initComponents();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        t= (javax.swing.table.DefaultTableModel) tabla_cheque.getModel();
        t1= (javax.swing.table.DefaultTableModel) tabla_tarjeta.getModel();
       // cargar_tabla("nombre","");
        tabla_cheque.getTableHeader().setReorderingAllowed(false);
        tabla_tarjeta.getTableHeader().setReorderingAllowed(false);
       // jRadioButton1.setSelected(true);
        this.formulario = formulario;
       // txt_buscar.requestFocus();
       combo();
       combo_entidad.requestFocus();
       t.setRowCount(0);
       t1.setRowCount(0);
       if(!pasar.equals("")){
           cargar_tabla(pasar);
       }
       if(!pasar1.equals("")){
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_cheque = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        btn_agregar_cama = new javax.swing.JButton();
        btn_quitar_cama = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        combo_entidad = new javax.swing.JComboBox<>();
        btn_editar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        txt_monto = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser("dd/MM/yyyy","##/##/####",'_');
        jLabel22 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser("dd/MM/yyyy","##/##/####",'_');
        jLabel24 = new javax.swing.JLabel();
        txt_nro_cheque = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_titular = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_tarjeta = new javax.swing.JTable();
        btn_agregar_cama1 = new javax.swing.JButton();
        btn_quitar_cama1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        combo_marca = new javax.swing.JComboBox<>();
        btn_editar1 = new javax.swing.JButton();
        btn_limpiar1 = new javax.swing.JButton();
        combo_tipo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        combo_entidad1 = new javax.swing.JComboBox<>();
        combo_procesadora = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_monto1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_ticket = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla_cheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Entidad", "Titular", "Monto", "Nro Cheque", "Emision", "Vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_cheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_chequeMousePressed(evt);
            }
        });
        tabla_cheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_chequeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_chequeKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_cheque);

        jLabel20.setText("Monto :");

        btn_agregar_cama.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar_cama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/mas2.png"))); // NOI18N
        btn_agregar_cama.setText("Agregar");
        btn_agregar_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_camaActionPerformed(evt);
            }
        });

        btn_quitar_cama.setBackground(new java.awt.Color(255, 255, 255));
        btn_quitar_cama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/menos.png"))); // NOI18N
        btn_quitar_cama.setText("Quitar");
        btn_quitar_cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitar_camaActionPerformed(evt);
            }
        });

        jLabel19.setText("Entidad :");

        combo_entidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_entidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_entidadFocusGained(evt);
            }
        });
        combo_entidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_entidadPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_entidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_entidadActionPerformed(evt);
            }
        });
        combo_entidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_entidadKeyPressed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/edit1.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/delete2.png"))); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        txt_monto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_montoFocusLost(evt);
            }
        });
        txt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_montoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_montoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_montoKeyTyped(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Emision :");

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("Vencimiento :");

        txt_nro_cheque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nro_chequeFocusLost(evt);
            }
        });
        txt_nro_cheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nro_chequeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nro_chequeKeyTyped(evt);
            }
        });

        jLabel21.setText("Nro Cheque :");

        txt_titular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_titularFocusLost(evt);
            }
        });
        txt_titular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_titularKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_titularKeyTyped(evt);
            }
        });

        jLabel23.setText("Titular :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel22))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(combo_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_titular, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nro_cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_agregar_cama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_quitar_cama, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_quitar_cama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_agregar_cama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_monto)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_nro_cheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/repetir.png"))); // NOI18N
        btn_actualizar.setText("Deshacer");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/agregar.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/aprobar.png"))); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btn_actualizar)
                .addGap(22, 22, 22)
                .addComponent(btn_cancelar)
                .addGap(22, 22, 22)
                .addComponent(btn_agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/atras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 175, 178));
        jLabel3.setText("Detalle Cobro");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla_tarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Marca", "Cod", "Tipo", "Cod", "Entidad", "Cod", "Procesadora", "Monto", "Serie", "Ticket"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_tarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_tarjetaMousePressed(evt);
            }
        });
        tabla_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabla_tarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabla_tarjetaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_tarjeta);

        btn_agregar_cama1.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar_cama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/mas2.png"))); // NOI18N
        btn_agregar_cama1.setText("Agregar");
        btn_agregar_cama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_cama1ActionPerformed(evt);
            }
        });

        btn_quitar_cama1.setBackground(new java.awt.Color(255, 255, 255));
        btn_quitar_cama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/menos.png"))); // NOI18N
        btn_quitar_cama1.setText("Quitar");
        btn_quitar_cama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitar_cama1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Marca :");

        combo_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_marcaFocusGained(evt);
            }
        });
        combo_marca.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_marcaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_marcaActionPerformed(evt);
            }
        });
        combo_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_marcaKeyPressed(evt);
            }
        });

        btn_editar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/edit1.png"))); // NOI18N
        btn_editar1.setText("Editar");
        btn_editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar1ActionPerformed(evt);
            }
        });

        btn_limpiar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos_formularios/delete2.png"))); // NOI18N
        btn_limpiar1.setText("Limpiar");
        btn_limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar1ActionPerformed(evt);
            }
        });

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_tipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_tipoFocusGained(evt);
            }
        });
        combo_tipo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_tipoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });
        combo_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_tipoKeyPressed(evt);
            }
        });

        jLabel29.setText("Tipo :");

        combo_entidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_entidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_entidad1FocusGained(evt);
            }
        });
        combo_entidad1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_entidad1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_entidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_entidad1ActionPerformed(evt);
            }
        });
        combo_entidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_entidad1KeyPressed(evt);
            }
        });

        combo_procesadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_procesadora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_procesadoraFocusGained(evt);
            }
        });
        combo_procesadora.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_procesadoraPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo_procesadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_procesadoraActionPerformed(evt);
            }
        });
        combo_procesadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combo_procesadoraKeyPressed(evt);
            }
        });

        jLabel30.setText("Procesadora :");

        jLabel26.setText("Entidad :");

        txt_monto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_monto1FocusLost(evt);
            }
        });
        txt_monto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_monto1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_monto1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_monto1KeyTyped(evt);
            }
        });

        jLabel27.setText("Monto :");

        txt_serie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_serieFocusLost(evt);
            }
        });
        txt_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serieActionPerformed(evt);
            }
        });
        txt_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serieKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serieKeyTyped(evt);
            }
        });

        jLabel28.setText("Serie :");

        txt_ticket.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ticketFocusLost(evt);
            }
        });
        txt_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ticketKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ticketKeyTyped(evt);
            }
        });

        jLabel31.setText("Ticket :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_procesadora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_entidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_serie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ticket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_monto1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_agregar_cama1)
                                .addGap(6, 6, 6)
                                .addComponent(btn_quitar_cama1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_limpiar1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txt_monto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(combo_entidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(combo_procesadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(combo_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_quitar_cama1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_agregar_cama1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_editar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       btn_aceptar.doClick();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
     /*   jRadioButton1.setSelected(true);
        txt_buscar.setText("");
        cargar_tabla("nombre", "");*/
     if(t.getRowCount()>0){
         t.setRowCount(0);
     }
     
     if(t1.getRowCount()>0){
         t1.setRowCount(0);
     }
     
     f = -1;
       c = -1;
       tabla = null;
       precio=0;
     
     btn_limpiar.doClick();
     btn_limpiar1.doClick();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
    //    menu.menu.llamar_internal(new referenciales.empleado());
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
       // referenciales.huespedes.buscador_personas("1");
       
       
       
       
           
           f = tabla_cheque.getRowCount();
           c = 6;
           tabla = new String[f][c];
           
           for (int c1=0; c1<c;c1++){
               for(int f1=0; f1<f;f1++){
                   if(c1==0){
                      tabla[f1][c1] = tabla_cheque.getValueAt(f1,0).toString();
                      precio += Integer.parseInt(tabla_cheque.getValueAt(f1,3).toString().replace(".",""));
                   }else if(c1==1){
                      tabla[f1][c1] = tabla_cheque.getValueAt(f1,2).toString();
                   }else if(c1==2){
                      tabla[f1][c1] = tabla_cheque.getValueAt(f1,3).toString().replace(".", "");
                   }else if(c1==3){
                      tabla[f1][c1] = tabla_cheque.getValueAt(f1,4).toString();
                   }else if(c1==4){
                     tabla[f1][c1] = con.convertir_fecha(tabla_cheque.getValueAt(f1,5).toString());
                   }else if(c1==5){
                     tabla[f1][c1] = con.convertir_fecha(tabla_cheque.getValueAt(f1,6).toString());
                   }
               }
           }
           
       
       
       if(formulario.equals("cobros")){
           if(tabla_cheque.getRowCount()<=0 ){
      
            movimientos.cobros.cobros.detalle_cobros(null, f, c, precio);
            
           }else{
           
           movimientos.cobros.cobros.detalle_cobros(tabla, f, c, precio);
           }
       }
            precio=0;
           f = tabla_tarjeta.getRowCount();
           c = 8;
           tabla = new String[f][c];
           
           for (int c1=0; c1<c;c1++){
               for(int f1=0; f1<f;f1++){
                   if(c1==0){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,0).toString();
                      precio += Integer.parseInt(tabla_tarjeta.getValueAt(f1,8).toString().replace(".",""));
                   }else if(c1==1){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,2).toString();
                   }else if(c1==2){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,4).toString();
                   }else if(c1==3){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,6).toString();
                   }else if(c1==4){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,7).toString();
                   }else if(c1==5){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,8).toString().replace(".", "");
                   }else if(c1==6){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,9).toString();
                   }else if(c1==7){
                      tabla[f1][c1] = tabla_tarjeta.getValueAt(f1,10).toString();
                   }
               }
           }
           
           
           if(formulario.equals("cobros")){
               
            if(tabla_tarjeta.getRowCount()<=0){
      
            movimientos.cobros.cobros.detalle_cobros1(null, f, c, precio);
            }else{
              
            movimientos.cobros.cobros.detalle_cobros1(tabla, f, c, precio);
            }
           }
           
           
       
       
       
       f = -1;
       c = -1;
       tabla = null;
       precio=0;
       
      // dispose();
        moveToBack();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void tabla_chequeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_chequeKeyReleased

    
       
    }//GEN-LAST:event_tabla_chequeKeyReleased

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       //btn_aceptar.doClick();
       btn_actualizar.doClick();
       btn_aceptar.doClick();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tabla_chequeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_chequeMousePressed

    }//GEN-LAST:event_tabla_chequeMousePressed

    private void tabla_chequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_chequeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          //  btn_aceptar.doClick();
        }
    }//GEN-LAST:event_tabla_chequeKeyPressed

    private void btn_agregar_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_camaActionPerformed
        if (txt_monto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar monto");
            txt_monto.requestFocus();
        }else if (txt_titular.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar titular");
            txt_nro_cheque.requestFocus();
        }else if (txt_nro_cheque.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar cheque");
            txt_nro_cheque.requestFocus();
        }else if (jDateChooser1.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Debe cargar emision");
            jDateChooser1.requestFocus();
        }else if (jDateChooser2.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Debe cargar vencimiento");
            jDateChooser2.requestFocus();
        }else if(combo_entidad.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar entidad");
            combo_entidad.requestFocus();
        }else if(jDateChooser1.getDate().compareTo(jDateChooser2.getDate())>-1){
            JOptionPane.showMessageDialog(null, "fecha emision mayor o igual a fecha vencimiento");
            combo_entidad.requestFocus();
        }else if(con.fechadmy(jDateChooser1.getDate()).equals(con.fechadmy(jDateChooser2.getDate()))){
            JOptionPane.showMessageDialog(null, "fecha emision igual a fecha vencimiento");
            combo_entidad.requestFocus();
        }else {
            cargar_detalle();
            combo_entidad.requestFocus();
        }
        
              
    }//GEN-LAST:event_btn_agregar_camaActionPerformed

    private void btn_quitar_camaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitar_camaActionPerformed
        if (tabla_cheque.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila", "Atencion",
                JOptionPane.WARNING_MESSAGE);

        } else {
            int mensaje = JOptionPane.showConfirmDialog(null, "Desea eliminar la fila seleccionada", "Atencion",
                JOptionPane.WARNING_MESSAGE, JOptionPane.QUESTION_MESSAGE);
            if (mensaje == 0) {
                javax.swing.table.DefaultTableModel tab = (javax.swing.table.DefaultTableModel) tabla_cheque.getModel();
                tab.removeRow(tabla_cheque.getSelectedRow());

            }
           // txt_telefono.setText("");
            
            btn_limpiar.doClick();
        }
    }//GEN-LAST:event_btn_quitar_camaActionPerformed

    private void combo_entidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_entidadFocusGained
        combo_entidad.showPopup();
    }//GEN-LAST:event_combo_entidadFocusGained

    private void combo_entidadPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_entidadPopupMenuWillBecomeInvisible
        txt_monto.requestFocus();
    }//GEN-LAST:event_combo_entidadPopupMenuWillBecomeInvisible

    private void combo_entidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_entidadActionPerformed
       
    }//GEN-LAST:event_combo_entidadActionPerformed

    private void combo_entidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_entidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txt_monto.requestFocus();
        }
    }//GEN-LAST:event_combo_entidadKeyPressed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
         if (tabla_cheque.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila", "Atencion",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        if (txt_monto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar monto");
            txt_monto.requestFocus();
        }else if (txt_titular.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar titular");
            txt_nro_cheque.requestFocus();
        }else if (txt_nro_cheque.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar cheque");
            txt_nro_cheque.requestFocus();
        }else if (jDateChooser1.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Debe cargar emision");
            jDateChooser1.requestFocus();
        }else if (jDateChooser2.getDate()==null) {
            JOptionPane.showMessageDialog(null, "Debe cargar vencimiento");
            jDateChooser2.requestFocus();
        }else if(combo_entidad.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar entidad");
            combo_entidad.requestFocus();
        }else if(jDateChooser1.getDate().compareTo(jDateChooser2.getDate())>-1){
            JOptionPane.showMessageDialog(null, "fecha emision mayor o igual a fecha vencimiento");
            combo_entidad.requestFocus();
        }else if(con.fechadmy(jDateChooser1.getDate()).equals(con.fechadmy(jDateChooser2.getDate()))){
            JOptionPane.showMessageDialog(null, "fecha emision igual a fecha vencimiento");
            combo_entidad.requestFocus();
        } else {
      
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea editar la fila seleccionada", "Atencion",
        JOptionPane.WARNING_MESSAGE, JOptionPane.QUESTION_MESSAGE);
        if (mensaje == 0) {
            javax.swing.table.DefaultTableModel tab = (javax.swing.table.DefaultTableModel) tabla_cheque.getModel();
            tab.removeRow(tabla_cheque.getSelectedRow());
            cargar_detalle();
            combo_entidad.requestFocus();
        }else {
        btn_limpiar.doClick();
        }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
     //  txt_telefono.setText("");
       txt_monto.setText("");
       txt_titular.setText("");
       txt_nro_cheque.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
       combo_entidad.setSelectedIndex(-1);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txt_nro_cheque.requestFocus();
        }
    }//GEN-LAST:event_txt_montoKeyPressed

    private void txt_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyTyped
       // con.validar_campos(new int[]{39, 126}, "letras_y_numeros", evt, new int[]{47, 164, 165, 209, 241});
       if(txt_monto.getText().length()>=18){
           evt.consume();
        }
       con.validar_campos("numeros", evt);
    }//GEN-LAST:event_txt_montoKeyTyped

    private void txt_montoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_montoFocusLost
      
    }//GEN-LAST:event_txt_montoFocusLost

    private void txt_nro_chequeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nro_chequeFocusLost
       
    }//GEN-LAST:event_txt_nro_chequeFocusLost

    private void txt_nro_chequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_chequeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_chequeKeyPressed

    private void txt_nro_chequeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_chequeKeyTyped
        con.validar_campos("numeros", evt);
    }//GEN-LAST:event_txt_nro_chequeKeyTyped

    private void tabla_tarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_tarjetaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_tarjetaMousePressed

    private void tabla_tarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_tarjetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_tarjetaKeyPressed

    private void tabla_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabla_tarjetaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_tarjetaKeyReleased

    private void btn_agregar_cama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_cama1ActionPerformed
        if(combo_tipo.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar tipo");
            combo_entidad.requestFocus();
        }else if(combo_marca.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar marca");
            combo_marca.requestFocus();
        }else if(combo_entidad1.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar entidad");
            combo_entidad1.requestFocus();
        }else if(combo_procesadora.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar procesadora");
            combo_procesadora.requestFocus();
        }else if (txt_monto1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar monto");
            txt_monto1.requestFocus();
        }else if (txt_serie.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar serie");
            txt_serie.requestFocus();
        }else if (txt_ticket.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar ticket");
            txt_ticket.requestFocus();
        }else {
            cargar_detalle1();
            combo_marca.requestFocus();
        }
    }//GEN-LAST:event_btn_agregar_cama1ActionPerformed

    private void btn_quitar_cama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitar_cama1ActionPerformed
         if (tabla_tarjeta.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila", "Atencion",
                JOptionPane.WARNING_MESSAGE);

        } else {
            int mensaje = JOptionPane.showConfirmDialog(null, "Desea eliminar la fila seleccionada", "Atencion",
                JOptionPane.WARNING_MESSAGE, JOptionPane.QUESTION_MESSAGE);
            if (mensaje == 0) {
                javax.swing.table.DefaultTableModel tab = (javax.swing.table.DefaultTableModel) tabla_tarjeta.getModel();
                tab.removeRow(tabla_tarjeta.getSelectedRow());

            }
           // txt_telefono.setText("");
            btn_limpiar1.doClick();
        }
    }//GEN-LAST:event_btn_quitar_cama1ActionPerformed

    private void combo_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_marcaFocusGained
       combo_marca.showPopup();
    }//GEN-LAST:event_combo_marcaFocusGained

    private void combo_marcaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_marcaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_marcaPopupMenuWillBecomeInvisible

    private void combo_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_marcaActionPerformed
       
    }//GEN-LAST:event_combo_marcaActionPerformed

    private void combo_marcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_marcaKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          combo_tipo.requestFocus();
        }
    }//GEN-LAST:event_combo_marcaKeyPressed

    private void btn_editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar1ActionPerformed
       if (tabla_tarjeta.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una fila", "Atencion",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        if(combo_tipo.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar tipo");
            combo_entidad.requestFocus();
        }else if(combo_marca.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar marca");
            combo_marca.requestFocus();
        }else if(combo_entidad1.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar entidad");
            combo_entidad1.requestFocus();
        }else if(combo_procesadora.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Debe cargar procesadora");
            combo_procesadora.requestFocus();
        }else if (txt_monto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar monto");
            txt_monto.requestFocus();
        }else if (txt_serie.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar serie");
            txt_serie.requestFocus();
        }else if (txt_ticket.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe cargar ticket");
            txt_ticket.requestFocus();
        } else {
      
        int mensaje = JOptionPane.showConfirmDialog(null, "Desea editar la fila seleccionada", "Atencion",
        JOptionPane.WARNING_MESSAGE, JOptionPane.QUESTION_MESSAGE);
        if (mensaje == 0) {
            javax.swing.table.DefaultTableModel tab = (javax.swing.table.DefaultTableModel) tabla_tarjeta.getModel();
            tab.removeRow(tabla_tarjeta.getSelectedRow());
            cargar_detalle1();
            combo_tipo.requestFocus();
        }else {
        btn_limpiar1.doClick();
        }
        }
    }//GEN-LAST:event_btn_editar1ActionPerformed

    private void btn_limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar1ActionPerformed
 
       combo_tipo.setSelectedIndex(-1);
       combo_marca.setSelectedIndex(-1);
       combo_entidad1.setSelectedIndex(-1);
       combo_procesadora.setSelectedIndex(-1);
       txt_monto1.setText("");
       txt_serie.setText("");
       txt_ticket.setText("");
       
    }//GEN-LAST:event_btn_limpiar1ActionPerformed

    private void combo_tipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_tipoFocusGained
        combo_tipo.showPopup();
    }//GEN-LAST:event_combo_tipoFocusGained

    private void combo_tipoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_tipoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tipoPopupMenuWillBecomeInvisible

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed
       
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void combo_tipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_tipoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          combo_entidad1.requestFocus();
        }
    }//GEN-LAST:event_combo_tipoKeyPressed

    private void txt_titularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_titularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titularFocusLost

    private void txt_titularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_titularKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_agregar_cama.doClick();
        }
    }//GEN-LAST:event_txt_titularKeyPressed

    private void txt_titularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_titularKeyTyped
        con.validar_campos(new int[]{39, 126}, "letras_y_numeros", evt, new int[]{47, 164, 165, 209, 241});
    }//GEN-LAST:event_txt_titularKeyTyped

    private void combo_entidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_entidad1FocusGained
       combo_entidad1.showPopup();
    }//GEN-LAST:event_combo_entidad1FocusGained

    private void combo_entidad1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_entidad1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_entidad1PopupMenuWillBecomeInvisible

    private void combo_entidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_entidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_entidad1ActionPerformed

    private void combo_entidad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_entidad1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          combo_procesadora.requestFocus();
        }
    }//GEN-LAST:event_combo_entidad1KeyPressed

    private void combo_procesadoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_procesadoraFocusGained
       combo_procesadora.showPopup();
    }//GEN-LAST:event_combo_procesadoraFocusGained

    private void combo_procesadoraPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_procesadoraPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_procesadoraPopupMenuWillBecomeInvisible

    private void combo_procesadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_procesadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_procesadoraActionPerformed

    private void combo_procesadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_procesadoraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txt_monto1.requestFocus();
        }
    }//GEN-LAST:event_combo_procesadoraKeyPressed

    private void txt_monto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_monto1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_monto1FocusLost

    private void txt_monto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txt_serie.requestFocus();
        }
    }//GEN-LAST:event_txt_monto1KeyPressed

    private void txt_monto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto1KeyTyped
        if(txt_monto1.getText().length()>=18){
           evt.consume();
        }
        con.validar_campos("numeros", evt);
    }//GEN-LAST:event_txt_monto1KeyTyped

    private void txt_serieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_serieFocusLost
      
    }//GEN-LAST:event_txt_serieFocusLost

    private void txt_serieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serieKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txt_ticket.requestFocus();
        }
    }//GEN-LAST:event_txt_serieKeyPressed

    private void txt_serieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serieKeyTyped
      con.validar_campos("numeros", evt);
    }//GEN-LAST:event_txt_serieKeyTyped

    private void txt_ticketFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ticketFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ticketFocusLost

    private void txt_ticketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ticketKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_agregar_cama1.doClick();
        }
    }//GEN-LAST:event_txt_ticketKeyPressed

    private void txt_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ticketKeyTyped
        con.validar_campos("numeros", evt);
    }//GEN-LAST:event_txt_ticketKeyTyped

    private void txt_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serieActionPerformed

    private void txt_montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyReleased
        formato_numeros(txt_monto);
    }//GEN-LAST:event_txt_montoKeyReleased

    private void txt_monto1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto1KeyReleased
       formato_numeros(txt_monto1);
    }//GEN-LAST:event_txt_monto1KeyReleased
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregar_cama;
    private javax.swing.JButton btn_agregar_cama1;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_editar1;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_limpiar1;
    private javax.swing.JButton btn_quitar_cama;
    private javax.swing.JButton btn_quitar_cama1;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JComboBox<String> combo_entidad;
    private static javax.swing.JComboBox<String> combo_entidad1;
    private static javax.swing.JComboBox<String> combo_marca;
    private static javax.swing.JComboBox<String> combo_procesadora;
    private static javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla_cheque;
    private javax.swing.JTable tabla_tarjeta;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_monto1;
    private javax.swing.JTextField txt_nro_cheque;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_ticket;
    private javax.swing.JTextField txt_titular;
    // End of variables declaration//GEN-END:variables

    
     private void combo() {         
         cargaCombo(combo_entidad, "SELECT CONCAT(id,'-',descripcion)\n" +
                                    "FROM entidad\n" +
                                    "ORDER BY CONCAT(id,'-',descripcion)\n" +
                                    "","CONCAT(id,'-',descripcion)");
         
         cargaCombo(combo_entidad1, "SELECT CONCAT(id,'-',descripcion)\n" +
                                    "FROM entidad\n" +
                                    "ORDER BY CONCAT(id,'-',descripcion)\n" +
                                    "","CONCAT(id,'-',descripcion)");
         
         cargaCombo(combo_marca, "SELECT CONCAT(id,'-',descripcion)\n" +
                                    "FROM marca_tarjeta\n" +
                                    "ORDER BY CONCAT(id,'-',descripcion)\n" +
                                    "","CONCAT(id,'-',descripcion)");
         
         cargaCombo(combo_tipo, "SELECT CONCAT(id,'-',descripcion)\n" +
                                    "FROM tipo_tarjeta\n" +
                                    "ORDER BY CONCAT(id,'-',descripcion)\n" +
                                    "","CONCAT(id,'-',descripcion)");
         
         cargaCombo(combo_procesadora, "SELECT CONCAT(id,'-',descripcion)\n" +
                                    "FROM procesadora\n" +
                                    "ORDER BY CONCAT(id,'-',descripcion)\n" +
                                    "","CONCAT(id,'-',descripcion)");
        
       // cargaCombo(combo_camas, "SELECT descripcion FROM cama order by descripcion", "descripcion");
    }
     
    
    
    private void cargaCombo(JComboBox cbo, String sql, String columna) {
        try {
            cbo.removeAllItems();
            con.sentencia = con.conexion.createStatement();
            con.resultado = con.sentencia.executeQuery(sql);
            while (con.resultado.next()) {
                if(columna.equals("descripcion")){
                    cbo.addItem(con.resultado.getString("descripcion"));
                }else if(columna.equals("nombre")){
                    cbo.addItem(con.resultado.getString("nombre"));
                }else if(columna.equals("CONCAT(id,'-',descripcion)")){
                    cbo.addItem(con.resultado.getString("CONCAT(id,'-',descripcion)"));
                }
                
            }
            cbo.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(tarifas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    
   
    
 
     private void cargar_detalle() {
         
         
         String identi = con.capturavalorcombo(combo_entidad);
       
        String entidad = con.BuscaCol("SELECT descripcion\n" +
                                        "FROM entidad \n" +
                                        "WHERE id ='" + identi + "'");
        
        
        
        
            t.addRow(new Object[]{identi, entidad, txt_titular.getText(), num.format(Long.parseLong(txt_monto.getText().replace(".",""))), 
                txt_nro_cheque.getText(),fec.format(jDateChooser1.getDate()),
                fec.format(jDateChooser2.getDate())});
        
                
        
    }
     
     
     private void cargar_detalle1() {
         
         
        String id_marca = con.capturavalorcombo(combo_marca);
       
        String marca = con.BuscaCol("SELECT descripcion\n" +
                                        "FROM marca_tarjeta \n" +
                                        "WHERE id ='" + id_marca + "'");
        
        
        String id_tipo = con.capturavalorcombo(combo_tipo);
       
        String tipo = con.BuscaCol("SELECT descripcion\n" +
                                        "FROM tipo_tarjeta \n" +
                                        "WHERE id ='" + id_tipo + "'");
        
        String identi = con.capturavalorcombo(combo_entidad1);
       
        String entidad = con.BuscaCol("SELECT descripcion\n" +
                                        "FROM entidad \n" +
                                        "WHERE id ='" + identi + "'");
        
        String id_proce = con.capturavalorcombo(combo_procesadora);
       
        String procesadora = con.BuscaCol("SELECT descripcion\n" +
                                        "FROM procesadora \n" +
                                        "WHERE id ='" + id_proce + "'");
        
            t1.addRow(new Object[]{id_marca,marca,id_tipo,tipo, identi,entidad,id_proce, procesadora,
            num.format(Long.parseLong(txt_monto1.getText().replace(".",""))),txt_serie.getText(),txt_ticket.getText()});
        
    }
     
     
     private boolean cuentaid(String id, javax.swing.JTable tabla) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            String vcod = tabla.getValueAt(i, 0).toString();
            if (id.equals(vcod)) {
                JOptionPane.showMessageDialog(null, "Codigo ingresado ya existe en el detalle");
                return false;
            }
        }
        return true;
    }
    
    
    
     
     /* private boolean cuentaid(String id,javax.swing.JTable tabla, int posicion) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            String vcod = tabla.getValueAt(i, posicion).toString();
            if (id.equals(vcod)) {
                JOptionPane.showMessageDialog(null, "Codigo ingresado ya existe en el detalle");
                return false;
            }
        }
        return true;
    }*/

     
     
      private void cargar_tabla(String id) {
        
        try {
            
            String sql="";
            
         
            
            sql = "SELECT r.id_habitacion, h.descripcion, h.capacidad,\n" +
                    " r.entrada, r.hora_entrada, r.salida, r.hora_salida\n" +
                    "FROM estadia_habitaciones r\n" +
                    "LEFT JOIN habitaciones h ON h.id = r.id_habitacion\n" +
                    "WHERE r.id_estadia = "+id+" ";
            
           
            
            t.setRowCount(0);
            con.sentencia = con.conexion.createStatement();
            con.resultado = con.sentencia.executeQuery(sql);
            while (con.resultado.next()) {
                t.addRow(new Object[]{con.resultado.getInt("r.id_habitacion"), 
                    con.resultado.getString("h.descripcion"),
                    con.resultado.getString("h.capacidad"),
                    fec.format(con.resultado.getDate("r.entrada")),
                    con.resultado.getString("r.hora_entrada"),
                    fec.format(con.resultado.getDate("r.salida")),
                    con.resultado.getString("r.hora_salida")});
                
            }
            
            
            sql = "SELECT p.id, p.nro_documento, CONCAT(p.nombre,' ',p.apellido),\n" +
                    "r.habitacion_id, hh.descripcion\n" +
                    "FROM estadia_huespedes r\n" +
                    "LEFT JOIN huespedes h ON h.id = r.huespedes_id\n" +
                    "LEFT JOIN persona p ON p.id = h.persona_id\n" +
                    "LEFT JOIN habitaciones hh ON hh.id = r.habitacion_id\n" +
                    "WHERE r.id_estadia = "+id+" ";
            
           
            
            t1.setRowCount(0);
            con.sentencia = con.conexion.createStatement();
            con.resultado = con.sentencia.executeQuery(sql);
            while (con.resultado.next()) {
                t1.addRow(new Object[]{con.resultado.getInt("p.id"), 
                    con.resultado.getString("p.nro_documento"),
                    con.resultado.getString("CONCAT(p.nombre,' ',p.apellido)"),
                    con.resultado.getString("r.habitacion_id"),
                    con.resultado.getString("hh.descripcion")});
                
            }  
        
        
        } catch (SQLException ex) {
            Logger.getLogger(buscador_servicios.class.getName()).log(Level.SEVERE, null, ex);
        }
}
      
      
      
      
      public void formato_hora(JTextField campo, KeyEvent e) { 
        String hora = campo.getText().trim().replace(":", "");
         
        String var, var1;
        
        if(hora.length()<=2){
            campo.setText(hora);
        }else if(hora.length()==3){
            var = hora.substring(0, 2);
            var1 = hora.substring(2, 3);
            campo.setText(var+":"+var1);
        }else if(hora.length()==4){
            var = hora.substring(0, 2);
            var1 = hora.substring(2, 4);
            campo.setText(var+":"+var1);
        }else if(hora.length()>=5){
            var = hora.substring(0, 2);
            var1 = hora.substring(2, 4);
            campo.setText(var+":"+var1);
        }
        
       
    }
      
      long numero;
      
      private void formato_numeros(JTextField campo) {
        if (!campo.getText().trim().isEmpty()) {
            // System.out.println(campo.getText().length());
            // System.out.println(numero);
            numero = Long.parseLong(campo.getText().replace(".", ""));
            campo.setText(num.format(numero));
            // }
        }
    }

   
}
